# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stairwell_openapi_client.api.hostnames_api import HostnamesApi  # noqa: E501


class TestHostnamesApi(unittest.TestCase):
    """HostnamesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HostnamesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_hostnames_create_comment(self) -> None:
        """Test case for hostnames_create_comment

        CreateComment  # noqa: E501
        """
        pass

    def test_hostnames_create_opinion(self) -> None:
        """Test case for hostnames_create_opinion

        CreateOpinion  # noqa: E501
        """
        pass

    def test_hostnames_create_tag(self) -> None:
        """Test case for hostnames_create_tag

        CreateTag  # noqa: E501
        """
        pass

    def test_hostnames_delete_tag(self) -> None:
        """Test case for hostnames_delete_tag

        DeleteTag  # noqa: E501
        """
        pass

    def test_hostnames_get_hostname_metadata(self) -> None:
        """Test case for hostnames_get_hostname_metadata

        GetHostnameMetadata  # noqa: E501
        """
        pass

    def test_hostnames_get_tag(self) -> None:
        """Test case for hostnames_get_tag

        GetTag  # noqa: E501
        """
        pass

    def test_hostnames_list_comments(self) -> None:
        """Test case for hostnames_list_comments

        ListComments  # noqa: E501
        """
        pass

    def test_hostnames_list_opinions(self) -> None:
        """Test case for hostnames_list_opinions

        ListOpinions  # noqa: E501
        """
        pass

    def test_hostnames_list_tags(self) -> None:
        """Test case for hostnames_list_tags

        ListTags  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
