# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stairwell_openapi_client.api.objects_api import ObjectsApi  # noqa: E501


class TestObjectsApi(unittest.TestCase):
    """ObjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_objects_create_comment(self) -> None:
        """Test case for objects_create_comment

        CreateComment  # noqa: E501
        """
        pass

    def test_objects_create_opinion(self) -> None:
        """Test case for objects_create_opinion

        CreateOpinion  # noqa: E501
        """
        pass

    def test_objects_create_tag(self) -> None:
        """Test case for objects_create_tag

        CreateTag  # noqa: E501
        """
        pass

    def test_objects_delete_tag(self) -> None:
        """Test case for objects_delete_tag

        DeleteTag  # noqa: E501
        """
        pass

    def test_objects_download_object(self) -> None:
        """Test case for objects_download_object

        DownloadObject  # noqa: E501
        """
        pass

    def test_objects_get_object_detonation(self) -> None:
        """Test case for objects_get_object_detonation

        GetObjectDetonation  # noqa: E501
        """
        pass

    def test_objects_get_object_metadata(self) -> None:
        """Test case for objects_get_object_metadata

        GetObjectMetadata  # noqa: E501
        """
        pass

    def test_objects_get_tag(self) -> None:
        """Test case for objects_get_tag

        GetTag  # noqa: E501
        """
        pass

    def test_objects_list_comments(self) -> None:
        """Test case for objects_list_comments

        ListComments  # noqa: E501
        """
        pass

    def test_objects_list_object_metadata(self) -> None:
        """Test case for objects_list_object_metadata

        ListObjectMetadata  # noqa: E501
        """
        pass

    def test_objects_list_object_sightings(self) -> None:
        """Test case for objects_list_object_sightings

        ListObjectSightings  # noqa: E501
        """
        pass

    def test_objects_list_object_variants(self) -> None:
        """Test case for objects_list_object_variants

        ListObjectVariants  # noqa: E501
        """
        pass

    def test_objects_list_opinions(self) -> None:
        """Test case for objects_list_opinions

        ListOpinions  # noqa: E501
        """
        pass

    def test_objects_list_tags(self) -> None:
        """Test case for objects_list_tags

        ListTags  # noqa: E501
        """
        pass

    def test_objects_trigger_object_detonation(self) -> None:
        """Test case for objects_trigger_object_detonation

        TriggerObjectDetonation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
