# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stairwell_openapi_client.api.yara_rules_api import YaraRulesApi  # noqa: E501


class TestYaraRulesApi(unittest.TestCase):
    """YaraRulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = YaraRulesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_yara_rules_create_tag(self) -> None:
        """Test case for yara_rules_create_tag

        CreateTag  # noqa: E501
        """
        pass

    def test_yara_rules_create_yara_rule(self) -> None:
        """Test case for yara_rules_create_yara_rule

        CreateYaraRule  # noqa: E501
        """
        pass

    def test_yara_rules_delete_tag(self) -> None:
        """Test case for yara_rules_delete_tag

        DeleteTag  # noqa: E501
        """
        pass

    def test_yara_rules_delete_yara_rule(self) -> None:
        """Test case for yara_rules_delete_yara_rule

        DeleteYaraRule  # noqa: E501
        """
        pass

    def test_yara_rules_get_tag(self) -> None:
        """Test case for yara_rules_get_tag

        GetTag  # noqa: E501
        """
        pass

    def test_yara_rules_get_yara_rule(self) -> None:
        """Test case for yara_rules_get_yara_rule

        GetYaraRule  # noqa: E501
        """
        pass

    def test_yara_rules_list_tags(self) -> None:
        """Test case for yara_rules_list_tags

        ListTags  # noqa: E501
        """
        pass

    def test_yara_rules_list_yara_rules(self) -> None:
        """Test case for yara_rules_list_yara_rules

        ListYaraRules  # noqa: E501
        """
        pass

    def test_yara_rules_update_yara_rule(self) -> None:
        """Test case for yara_rules_update_yara_rule

        UpdateYaraRule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
