# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stairwell_openapi_client.api.assets_api import AssetsApi  # noqa: E501


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_assets_create_tag(self) -> None:
        """Test case for assets_create_tag

        CreateTag  # noqa: E501
        """
        pass

    def test_assets_delete_tag(self) -> None:
        """Test case for assets_delete_tag

        DeleteTag  # noqa: E501
        """
        pass

    def test_assets_get_asset(self) -> None:
        """Test case for assets_get_asset

        GetAsset  # noqa: E501
        """
        pass

    def test_assets_get_tag(self) -> None:
        """Test case for assets_get_tag

        GetTag  # noqa: E501
        """
        pass

    def test_assets_list_assets(self) -> None:
        """Test case for assets_list_assets

        ListAssets  # noqa: E501
        """
        pass

    def test_assets_list_tags(self) -> None:
        """Test case for assets_list_tags

        ListTags  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
