# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from stairwell_openapi_client.models.list_threat_report_matches_response import ListThreatReportMatchesResponse  # noqa: E501

class TestListThreatReportMatchesResponse(unittest.TestCase):
    """ListThreatReportMatchesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListThreatReportMatchesResponse:
        """Test ListThreatReportMatchesResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListThreatReportMatchesResponse`
        """
        model = ListThreatReportMatchesResponse()  # noqa: E501
        if include_optional:
            return ListThreatReportMatchesResponse(
                threat_report_matches = [
                    stairwell_openapi_client.models.threat_report_match.ThreatReportMatch(
                        object_metadata = stairwell_openapi_client.models.object_metadata.ObjectMetadata(
                            name = '', 
                            md5 = '', 
                            sha1 = '', 
                            sha256 = '', 
                            sha3256 = '', 
                            size = '', 
                            stairwell_first_seen_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            tags = [
                                stairwell_openapi_client.models.tag.Tag(
                                    name = '', 
                                    value = '', 
                                    environment = '', )
                                ], 
                            detonation = stairwell_openapi_client.models.object_detonation.ObjectDetonation(
                                name = '', 
                                overview = '', 
                                raw_triage_reports = {
                                    'key' : ''
                                    }, 
                                sample_id = '', 
                                files = [
                                    stairwell_openapi_client.models.file_action.FileAction(
                                        filename = '', 
                                        action = 'ACTION_UNSPECIFIED', )
                                    ], 
                                registry_keys = [
                                    stairwell_openapi_client.models.registry_key_action.RegistryKeyAction(
                                        registry_key = '', 
                                        action = 'ACTION_UNSPECIFIED', 
                                        registry_key_hive = 'REGISTRY_KEY_HIVE_UNSPECIFIED', )
                                    ], 
                                executed_commands = [
                                    ''
                                    ], 
                                mutexes = [
                                    ''
                                    ], 
                                signatures = [
                                    ''
                                    ], 
                                mitre_attack_ttps = [
                                    stairwell_openapi_client.models.mitre_attack_ttp.MitreAttackTTP(
                                        ttp = '', 
                                        signature = '', )
                                    ], 
                                created_services = [
                                    ''
                                    ], 
                                started_services = [
                                    ''
                                    ], 
                                dropped_files = [
                                    ''
                                    ], 
                                in_memory_files = [
                                    ''
                                    ], 
                                detections = [
                                    stairwell_openapi_client.models.detection.Detection(
                                        family = '', )
                                    ], ), 
                            mal_eval = stairwell_openapi_client.models.mal_eval.MalEval(
                                labels = [
                                    ''
                                    ], 
                                probability_bucket = 'PROBABILITY_BUCKET_UNSPECIFIED', 
                                severity = 'SEVERITY_UNSPECIFIED', ), 
                            environments = [
                                ''
                                ], 
                            yara_rule_matches = [
                                ''
                                ], 
                            network_indicators = stairwell_openapi_client.models.network_indicators.NetworkIndicators(
                                ip_addresses = [
                                    ''
                                    ], 
                                uninteresting_ip_addresses = [
                                    ''
                                    ], 
                                hostnames = [
                                    ''
                                    ], 
                                improbable_hostnames = [
                                    ''
                                    ], 
                                private_hostnames = [
                                    ''
                                    ], ), 
                            magic = '', 
                            mime_type = '', 
                            shannon_entropy = 1.337, 
                            imphash = '', 
                            imphash_sorted = '', 
                            tlsh = '', 
                            object_signature = stairwell_openapi_client.models.object_signature.ObjectSignature(
                                x509_certificates = [
                                    stairwell_openapi_client.models.x509_certificate.X509Certificate(
                                        signature = '', 
                                        issuer = '', 
                                        subject = '', 
                                        earliest_valid_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        latest_valid_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                    ], 
                                pkcs7_verification_result = 'PKCS7_VERIFICATION_RESULT_UNSPECIFIED', ), ), )
                    ],
                next_page_token = ''
            )
        else:
            return ListThreatReportMatchesResponse(
        )
        """

    def testListThreatReportMatchesResponse(self):
        """Test ListThreatReportMatchesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
