# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError
from typing import overload, Optional, Union, Awaitable

from typing_extensions import Annotated
from pydantic import Field, StrictBool, StrictInt, StrictStr

from typing import Optional

from stairwell_openapi_client.models.list_tags_response import ListTagsResponse
from stairwell_openapi_client.models.list_yara_rules_response import ListYaraRulesResponse
from stairwell_openapi_client.models.tag import Tag
from stairwell_openapi_client.models.yara_rule import YaraRule

from stairwell_openapi_client.api_client import ApiClient
from stairwell_openapi_client.api_response import ApiResponse
from stairwell_openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class YaraRulesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    async def yara_rules_create_tag(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], tag : Tag, **kwargs) -> Tag:  # noqa: E501
        """CreateTag  # noqa: E501

        Creates a new tag.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param tag: (required)
        :type tag: Tag
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Tag
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the yara_rules_create_tag_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.yara_rules_create_tag_with_http_info(environment, yara_rule, tag, **kwargs)  # noqa: E501

    @validate_arguments
    async def yara_rules_create_tag_with_http_info(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], tag : Tag, **kwargs) -> ApiResponse:  # noqa: E501
        """CreateTag  # noqa: E501

        Creates a new tag.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param tag: (required)
        :type tag: Tag
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Tag, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'environment',
            'yara_rule',
            'tag'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method yara_rules_create_tag" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['environment'] is not None:
            _path_params['environment'] = _params['environment']

        if _params['yara_rule'] is not None:
            _path_params['yaraRule'] = _params['yara_rule']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['tag'] is not None:
            _body_params = _params['tag']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['AuthToken']  # noqa: E501

        _response_types_map = {
            '200': "Tag",
        }

        return await self.api_client.call_api(
            '/v1/environments/{environment}/yaraRules/{yaraRule}/tags', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    async def yara_rules_create_yara_rule(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : YaraRule, **kwargs) -> YaraRule:  # noqa: E501
        """CreateYaraRule  # noqa: E501

        Gets metadata and rule definition.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: (required)
        :type yara_rule: YaraRule
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: YaraRule
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the yara_rules_create_yara_rule_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.yara_rules_create_yara_rule_with_http_info(environment, yara_rule, **kwargs)  # noqa: E501

    @validate_arguments
    async def yara_rules_create_yara_rule_with_http_info(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : YaraRule, **kwargs) -> ApiResponse:  # noqa: E501
        """CreateYaraRule  # noqa: E501

        Gets metadata and rule definition.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: (required)
        :type yara_rule: YaraRule
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(YaraRule, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'environment',
            'yara_rule'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method yara_rules_create_yara_rule" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['environment'] is not None:
            _path_params['environment'] = _params['environment']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['yara_rule'] is not None:
            _body_params = _params['yara_rule']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['AuthToken']  # noqa: E501

        _response_types_map = {
            '200': "YaraRule",
        }

        return await self.api_client.call_api(
            '/v1/environments/{environment}/yaraRules', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    async def yara_rules_delete_tag(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], tag : Annotated[StrictStr, Field(..., description="The tag id.")], **kwargs) -> None:  # noqa: E501
        """DeleteTag  # noqa: E501

        Deletes a tag.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param tag: The tag id. (required)
        :type tag: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the yara_rules_delete_tag_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.yara_rules_delete_tag_with_http_info(environment, yara_rule, tag, **kwargs)  # noqa: E501

    @validate_arguments
    async def yara_rules_delete_tag_with_http_info(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], tag : Annotated[StrictStr, Field(..., description="The tag id.")], **kwargs) -> ApiResponse:  # noqa: E501
        """DeleteTag  # noqa: E501

        Deletes a tag.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param tag: The tag id. (required)
        :type tag: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        _params = locals()

        _all_params = [
            'environment',
            'yara_rule',
            'tag'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method yara_rules_delete_tag" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['environment'] is not None:
            _path_params['environment'] = _params['environment']

        if _params['yara_rule'] is not None:
            _path_params['yaraRule'] = _params['yara_rule']

        if _params['tag'] is not None:
            _path_params['tag'] = _params['tag']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # authentication setting
        _auth_settings = ['AuthToken']  # noqa: E501

        _response_types_map = {}

        return await self.api_client.call_api(
            '/v1/environments/{environment}/yaraRules/{yaraRule}/tags/{tag}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    async def yara_rules_delete_yara_rule(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], force : Annotated[Optional[StrictBool], Field(description="Force deletion even if tags exist")] = None, **kwargs) -> None:  # noqa: E501
        """DeleteYaraRule  # noqa: E501

        Gets metadata and rule definition.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param force: Force deletion even if tags exist
        :type force: bool
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the yara_rules_delete_yara_rule_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.yara_rules_delete_yara_rule_with_http_info(environment, yara_rule, force, **kwargs)  # noqa: E501

    @validate_arguments
    async def yara_rules_delete_yara_rule_with_http_info(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], force : Annotated[Optional[StrictBool], Field(description="Force deletion even if tags exist")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """DeleteYaraRule  # noqa: E501

        Gets metadata and rule definition.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param force: Force deletion even if tags exist
        :type force: bool
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        _params = locals()

        _all_params = [
            'environment',
            'yara_rule',
            'force'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method yara_rules_delete_yara_rule" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['environment'] is not None:
            _path_params['environment'] = _params['environment']

        if _params['yara_rule'] is not None:
            _path_params['yaraRule'] = _params['yara_rule']


        # process the query parameters
        _query_params = []
        if _params.get('force') is not None:  # noqa: E501
            _query_params.append(('force', _params['force']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # authentication setting
        _auth_settings = ['AuthToken']  # noqa: E501

        _response_types_map = {}

        return await self.api_client.call_api(
            '/v1/environments/{environment}/yaraRules/{yaraRule}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    async def yara_rules_get_tag(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], tag : Annotated[StrictStr, Field(..., description="The tag id.")], **kwargs) -> Tag:  # noqa: E501
        """GetTag  # noqa: E501

        Gets a specified tag by name.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param tag: The tag id. (required)
        :type tag: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Tag
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the yara_rules_get_tag_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.yara_rules_get_tag_with_http_info(environment, yara_rule, tag, **kwargs)  # noqa: E501

    @validate_arguments
    async def yara_rules_get_tag_with_http_info(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], tag : Annotated[StrictStr, Field(..., description="The tag id.")], **kwargs) -> ApiResponse:  # noqa: E501
        """GetTag  # noqa: E501

        Gets a specified tag by name.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param tag: The tag id. (required)
        :type tag: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Tag, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'environment',
            'yara_rule',
            'tag'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method yara_rules_get_tag" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['environment'] is not None:
            _path_params['environment'] = _params['environment']

        if _params['yara_rule'] is not None:
            _path_params['yaraRule'] = _params['yara_rule']

        if _params['tag'] is not None:
            _path_params['tag'] = _params['tag']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['AuthToken']  # noqa: E501

        _response_types_map = {
            '200': "Tag",
        }

        return await self.api_client.call_api(
            '/v1/environments/{environment}/yaraRules/{yaraRule}/tags/{tag}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    async def yara_rules_get_yara_rule(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], **kwargs) -> YaraRule:  # noqa: E501
        """GetYaraRule  # noqa: E501

        Gets metadata and rule definition.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: YaraRule
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the yara_rules_get_yara_rule_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.yara_rules_get_yara_rule_with_http_info(environment, yara_rule, **kwargs)  # noqa: E501

    @validate_arguments
    async def yara_rules_get_yara_rule_with_http_info(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], **kwargs) -> ApiResponse:  # noqa: E501
        """GetYaraRule  # noqa: E501

        Gets metadata and rule definition.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(YaraRule, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'environment',
            'yara_rule'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method yara_rules_get_yara_rule" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['environment'] is not None:
            _path_params['environment'] = _params['environment']

        if _params['yara_rule'] is not None:
            _path_params['yaraRule'] = _params['yara_rule']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['AuthToken']  # noqa: E501

        _response_types_map = {
            '200': "YaraRule",
        }

        return await self.api_client.call_api(
            '/v1/environments/{environment}/yaraRules/{yaraRule}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    async def yara_rules_list_tags(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], page_size : Annotated[Optional[StrictInt], Field(description="The maximum number of tags to return. The service may return fewer than this value. If unspecified, at most 100 tags will be returned. The maximum value is 1000; values above 1000 will be coerced to 1000.")] = None, page_token : Annotated[Optional[StrictStr], Field(description="A page token, received from a previous `ListTags` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `ListTags` must match the call that provided the page token.")] = None, **kwargs) -> ListTagsResponse:  # noqa: E501
        """ListTags  # noqa: E501

        Gets the tags for the specified yara rule.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param page_size: The maximum number of tags to return. The service may return fewer than this value. If unspecified, at most 100 tags will be returned. The maximum value is 1000; values above 1000 will be coerced to 1000.
        :type page_size: int
        :param page_token: A page token, received from a previous `ListTags` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `ListTags` must match the call that provided the page token.
        :type page_token: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: ListTagsResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the yara_rules_list_tags_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.yara_rules_list_tags_with_http_info(environment, yara_rule, page_size, page_token, **kwargs)  # noqa: E501

    @validate_arguments
    async def yara_rules_list_tags_with_http_info(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], page_size : Annotated[Optional[StrictInt], Field(description="The maximum number of tags to return. The service may return fewer than this value. If unspecified, at most 100 tags will be returned. The maximum value is 1000; values above 1000 will be coerced to 1000.")] = None, page_token : Annotated[Optional[StrictStr], Field(description="A page token, received from a previous `ListTags` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `ListTags` must match the call that provided the page token.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """ListTags  # noqa: E501

        Gets the tags for the specified yara rule.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param page_size: The maximum number of tags to return. The service may return fewer than this value. If unspecified, at most 100 tags will be returned. The maximum value is 1000; values above 1000 will be coerced to 1000.
        :type page_size: int
        :param page_token: A page token, received from a previous `ListTags` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `ListTags` must match the call that provided the page token.
        :type page_token: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(ListTagsResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'environment',
            'yara_rule',
            'page_size',
            'page_token'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method yara_rules_list_tags" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['environment'] is not None:
            _path_params['environment'] = _params['environment']

        if _params['yara_rule'] is not None:
            _path_params['yaraRule'] = _params['yara_rule']


        # process the query parameters
        _query_params = []
        if _params.get('page_size') is not None:  # noqa: E501
            _query_params.append(('pageSize', _params['page_size']))

        if _params.get('page_token') is not None:  # noqa: E501
            _query_params.append(('pageToken', _params['page_token']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['AuthToken']  # noqa: E501

        _response_types_map = {
            '200': "ListTagsResponse",
        }

        return await self.api_client.call_api(
            '/v1/environments/{environment}/yaraRules/{yaraRule}/tags', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    async def yara_rules_list_yara_rules(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], page_size : Annotated[Optional[StrictInt], Field(description="The number of yara rules to return in a single page")] = None, page_token : Annotated[Optional[StrictStr], Field(description="The page token for getting successive pages")] = None, **kwargs) -> ListYaraRulesResponse:  # noqa: E501
        """ListYaraRules  # noqa: E501

        Gets metadata and rule definition.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param page_size: The number of yara rules to return in a single page
        :type page_size: int
        :param page_token: The page token for getting successive pages
        :type page_token: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: ListYaraRulesResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the yara_rules_list_yara_rules_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.yara_rules_list_yara_rules_with_http_info(environment, page_size, page_token, **kwargs)  # noqa: E501

    @validate_arguments
    async def yara_rules_list_yara_rules_with_http_info(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], page_size : Annotated[Optional[StrictInt], Field(description="The number of yara rules to return in a single page")] = None, page_token : Annotated[Optional[StrictStr], Field(description="The page token for getting successive pages")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """ListYaraRules  # noqa: E501

        Gets metadata and rule definition.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param page_size: The number of yara rules to return in a single page
        :type page_size: int
        :param page_token: The page token for getting successive pages
        :type page_token: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(ListYaraRulesResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'environment',
            'page_size',
            'page_token'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method yara_rules_list_yara_rules" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['environment'] is not None:
            _path_params['environment'] = _params['environment']


        # process the query parameters
        _query_params = []
        if _params.get('page_size') is not None:  # noqa: E501
            _query_params.append(('pageSize', _params['page_size']))

        if _params.get('page_token') is not None:  # noqa: E501
            _query_params.append(('pageToken', _params['page_token']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['AuthToken']  # noqa: E501

        _response_types_map = {
            '200': "ListYaraRulesResponse",
        }

        return await self.api_client.call_api(
            '/v1/environments/{environment}/yaraRules', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    async def yara_rules_update_yara_rule(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], yara_rule2 : YaraRule, update_mask : Annotated[Optional[StrictStr], Field(description="The fields of the yara rule to update. Currently supports status and definition.")] = None, **kwargs) -> YaraRule:  # noqa: E501
        """UpdateYaraRule  # noqa: E501

        Gets metadata and rule definition.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param yara_rule2: (required)
        :type yara_rule2: YaraRule
        :param update_mask: The fields of the yara rule to update. Currently supports status and definition.
        :type update_mask: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: YaraRule
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the yara_rules_update_yara_rule_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.yara_rules_update_yara_rule_with_http_info(environment, yara_rule, yara_rule2, update_mask, **kwargs)  # noqa: E501

    @validate_arguments
    async def yara_rules_update_yara_rule_with_http_info(self, environment : Annotated[StrictStr, Field(..., description="The environment id.")], yara_rule : Annotated[StrictStr, Field(..., description="The yaraRule id.")], yara_rule2 : YaraRule, update_mask : Annotated[Optional[StrictStr], Field(description="The fields of the yara rule to update. Currently supports status and definition.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """UpdateYaraRule  # noqa: E501

        Gets metadata and rule definition.  # noqa: E501

        :param environment: The environment id. (required)
        :type environment: str
        :param yara_rule: The yaraRule id. (required)
        :type yara_rule: str
        :param yara_rule2: (required)
        :type yara_rule2: YaraRule
        :param update_mask: The fields of the yara rule to update. Currently supports status and definition.
        :type update_mask: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(YaraRule, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'environment',
            'yara_rule',
            'yara_rule2',
            'update_mask'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method yara_rules_update_yara_rule" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['environment'] is not None:
            _path_params['environment'] = _params['environment']

        if _params['yara_rule'] is not None:
            _path_params['yaraRule'] = _params['yara_rule']


        # process the query parameters
        _query_params = []
        if _params.get('update_mask') is not None:  # noqa: E501
            _query_params.append(('updateMask', _params['update_mask']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['yara_rule2'] is not None:
            _body_params = _params['yara_rule2']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['AuthToken']  # noqa: E501

        _response_types_map = {
            '200': "YaraRule",
        }

        return await self.api_client.call_api(
            '/v1/environments/{environment}/yaraRules/{yaraRule}', 'PATCH',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
