# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class Comment(BaseModel):
    """
    Comment represents a key value pairing applied to particular entity. Only one of object, rule or asset may be specified.  # noqa: E501
    """
    body: StrictStr = Field(..., description="The body of the comment.")
    email: Optional[StrictStr] = Field(None, description="The email of the user who made the comment.")
    create_time: Optional[datetime] = Field(None, alias="createTime", description="The time when the comment was added.")
    environment: StrictStr = Field(..., description="the environment in which this tag will live.")
    __properties = ["body", "email", "createTime", "environment"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Comment:
        """Create an instance of Comment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "email",
                            "create_time",
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Comment:
        """Create an instance of Comment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Comment.parse_obj(obj)

        _obj = Comment.parse_obj({
            "body": obj.get("body"),
            "email": obj.get("email"),
            "create_time": obj.get("createTime"),
            "environment": obj.get("environment")
        })
        return _obj


