# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class MitreAttackTTP(BaseModel):
    """
    MitreAttackTTP contains the MITRE signatures which were observed during detonation.  # noqa: E501
    """
    ttp: Optional[StrictStr] = Field(None, description="TTP is a code indicating the signature which was observed. Code reference: https://attack.mitre.org/techniques/enterprise/")
    signature: Optional[StrictStr] = Field(None, description="Signature is the name of the signature which was observed.")
    __properties = ["ttp", "signature"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MitreAttackTTP:
        """Create an instance of MitreAttackTTP from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MitreAttackTTP:
        """Create an instance of MitreAttackTTP from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MitreAttackTTP.parse_obj(obj)

        _obj = MitreAttackTTP.parse_obj({
            "ttp": obj.get("ttp"),
            "signature": obj.get("signature")
        })
        return _obj


