# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from stairwell_openapi_client.models.object_metadata import ObjectMetadata

class ObjectVariant(BaseModel):
    """
    Contains metadata about an object and its similarity score to the original.  # noqa: E501
    """
    variant: Optional[ObjectMetadata] = None
    similarity: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The similarity to the origin file in terms of a percentage.")
    __properties = ["variant", "similarity"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ObjectVariant:
        """Create an instance of ObjectVariant from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of variant
        if self.variant:
            _dict['variant'] = self.variant.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ObjectVariant:
        """Create an instance of ObjectVariant from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ObjectVariant.parse_obj(obj)

        _obj = ObjectVariant.parse_obj({
            "variant": ObjectMetadata.from_dict(obj.get("variant")) if obj.get("variant") is not None else None,
            "similarity": obj.get("similarity")
        })
        return _obj


