# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, validator
from stairwell_openapi_client.models.object_metadata import ObjectMetadata
from stairwell_openapi_client.models.object_sighting import ObjectSighting
from stairwell_openapi_client.models.trigger_match_condition import TriggerMatchCondition

class TriggerMatch(BaseModel):
    """
    Contains data as to what object matched and why it matched a particular trigger.  # noqa: E501
    """
    name: Optional[StrictStr] = Field(default=None, description="Name of the trigger.")
    label: Optional[StrictStr] = Field(default=None, description="Label of the created trigger.")
    create_time: Optional[datetime] = Field(default=None, alias="createTime", description="The time when the match was created.")
    match_type: Optional[StrictStr] = Field(default=None, alias="matchType", description="Type of trigger match.")
    object_metadata: Optional[ObjectMetadata] = Field(default=None, alias="objectMetadata")
    object_sightings: Optional[conlist(ObjectSighting)] = Field(default=None, alias="objectSightings", description="All sightings data for object that matched.")
    trigger_condition: Optional[TriggerMatchCondition] = Field(default=None, alias="triggerCondition")
    __properties = ["name", "label", "createTime", "matchType", "objectMetadata", "objectSightings", "triggerCondition"]

    @validator('match_type')
    def match_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('MATCH_TYPE_UNSPECIFIED', 'OBJECT_SEEN', 'MAL_EVAL_MATCH', 'OBJECT_OPINION_MATCH', 'YARA_RULE_MATCH', 'THREAT_REPORT_MATCH'):
            raise ValueError("must be one of enum values ('MATCH_TYPE_UNSPECIFIED', 'OBJECT_SEEN', 'MAL_EVAL_MATCH', 'OBJECT_OPINION_MATCH', 'YARA_RULE_MATCH', 'THREAT_REPORT_MATCH')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TriggerMatch:
        """Create an instance of TriggerMatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "name",
                            "label",
                            "create_time",
                            "match_type",
                            "object_sightings",
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of object_metadata
        if self.object_metadata:
            _dict['objectMetadata'] = self.object_metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in object_sightings (list)
        _items = []
        if self.object_sightings:
            for _item in self.object_sightings:
                if _item:
                    _items.append(_item.to_dict())
            _dict['objectSightings'] = _items
        # override the default output from pydantic by calling `to_dict()` of trigger_condition
        if self.trigger_condition:
            _dict['triggerCondition'] = self.trigger_condition.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TriggerMatch:
        """Create an instance of TriggerMatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TriggerMatch.parse_obj(obj)

        _obj = TriggerMatch.parse_obj({
            "name": obj.get("name"),
            "label": obj.get("label"),
            "create_time": obj.get("createTime"),
            "match_type": obj.get("matchType"),
            "object_metadata": ObjectMetadata.from_dict(obj.get("objectMetadata")) if obj.get("objectMetadata") is not None else None,
            "object_sightings": [ObjectSighting.from_dict(_item) for _item in obj.get("objectSightings")] if obj.get("objectSightings") is not None else None,
            "trigger_condition": TriggerMatchCondition.from_dict(obj.get("triggerCondition")) if obj.get("triggerCondition") is not None else None
        })
        return _obj


