# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from stairwell_openapi_client.models.mal_eval import MalEval
from stairwell_openapi_client.models.opinion import Opinion
from stairwell_openapi_client.models.threat_report import ThreatReport

class TriggerMatchCondition(BaseModel):
    """
    Condition of the trigger which matched the object.  # noqa: E501
    """
    yara_rule_match: Optional[conlist(StrictStr)] = Field(default=None, alias="yaraRuleMatch", description="Yara rule names which triggered a match .")
    mal_eval: Optional[MalEval] = Field(default=None, alias="malEval")
    opinion: Optional[Opinion] = None
    threat_reports: Optional[conlist(ThreatReport)] = Field(default=None, alias="threatReports", description="Threat reports that triggered a match.")
    __properties = ["yaraRuleMatch", "malEval", "opinion", "threatReports"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TriggerMatchCondition:
        """Create an instance of TriggerMatchCondition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of mal_eval
        if self.mal_eval:
            _dict['malEval'] = self.mal_eval.to_dict()
        # override the default output from pydantic by calling `to_dict()` of opinion
        if self.opinion:
            _dict['opinion'] = self.opinion.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in threat_reports (list)
        _items = []
        if self.threat_reports:
            for _item in self.threat_reports:
                if _item:
                    _items.append(_item.to_dict())
            _dict['threatReports'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TriggerMatchCondition:
        """Create an instance of TriggerMatchCondition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TriggerMatchCondition.parse_obj(obj)

        _obj = TriggerMatchCondition.parse_obj({
            "yara_rule_match": obj.get("yaraRuleMatch"),
            "mal_eval": MalEval.from_dict(obj.get("malEval")) if obj.get("malEval") is not None else None,
            "opinion": Opinion.from_dict(obj.get("opinion")) if obj.get("opinion") is not None else None,
            "threat_reports": [ThreatReport.from_dict(_item) for _item in obj.get("threatReports")] if obj.get("threatReports") is not None else None
        })
        return _obj


