# coding: utf-8

"""
    Stairwell V1 HTTP APIs

    Restful APIs for the Stairwell platform. Most APIs expose named resources: each resource has a unique identifier that users use to reference that resource, and these names are what users should store as the canonical names for the resources. The base URL for this API is https://app.stairwell.com

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class X509Certificate(BaseModel):
    """
    A representation of an x509 certificate.  # noqa: E501
    """
    signature: Optional[StrictStr] = Field(None, description="An encoded hash representing the digital signature of the certificate.")
    issuer: Optional[StrictStr] = Field(None, description="The common name of the issuer of this certificate.")
    subject: Optional[StrictStr] = Field(None, description="The common name of the subject of this certificate.")
    earliest_valid_time: Optional[datetime] = Field(None, alias="earliestValidTime", description="The earliest time where this certificate is valid.")
    latest_valid_time: Optional[datetime] = Field(None, alias="latestValidTime", description="The latest time where this certificate is valid.")
    __properties = ["signature", "issuer", "subject", "earliestValidTime", "latestValidTime"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> X509Certificate:
        """Create an instance of X509Certificate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> X509Certificate:
        """Create an instance of X509Certificate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return X509Certificate.parse_obj(obj)

        _obj = X509Certificate.parse_obj({
            "signature": obj.get("signature"),
            "issuer": obj.get("issuer"),
            "subject": obj.get("subject"),
            "earliest_valid_time": obj.get("earliestValidTime"),
            "latest_valid_time": obj.get("latestValidTime")
        })
        return _obj


